models/__init__.py
from app import db

models/task.py
from app.models import db
# COMO UM MÉTODO CONSTRUTOR
class Task(db.Model):
    __tablename__ = 'taks'

    id = id.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)

    def __init__(self, title):
        self.title = title

    def to_dict(self):
        return {'id': self.id, 'title': self.title}
   
    @classmethod
    def create(cls, title):
        new_task = cls(title=title)
        db.session.add(new_task)
        db.session.commit
        return new_task

    @classmethod
    def update(cls, title, task_id):
        task = cls.query.get(task_id)
        if task:
            task.title = title
            db.session.commit()
        return task 
    
    @classmethod
    def delete(cls, task_id):
        task = cls.query.get(task_id)
        if task: 
            db.session.delete(task)
            db.session.commit()
        return task  

__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///prod.db'
    app.config['SQLALCHEMY_TRACK_MIDIFICATIONS'] = False

    db.init_app(app)
    migrate.init_app(app, db)

    from app.controllers.user_controller import user_bp
    from app.controllers.task_controller import task_bp

    app.register_blueprint(user_bp)
    app.register_blueprint(task_bp)

    @app.router('/')
    def home():
        return render_template('index.html')


controllers/__init__.py
from flask import Blueprint

controllers_bp = Blueprint('controllers', __name__)

controllers/task_controller.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models.task import Task
from app import db

# Blueprint
task_bp =  Blueprint('task_bp', __name__)

# construindo a minha rota 
@task_bp.route('/tasks', methods=['GET'])
def list_tasks(): 
    tasks = Task.query.all()
    return render_template('task_list.html', tasks=tasks)

@task_bp.route('/tasks/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        title = request.form['title']

        new_task = Task(title=title)
        db.session.add(new_task)
        db.session.commit
        return redirect(url_for('task_bp_list_tasks'))
    return render_template('create_task.html') 

@task_bp.route('task/update/<int:task_id>', methods=['GET', 'POST'])
def update_task(task_id):
    task = Task.query.get_or_404(task_id)
    if request.method == 'POST':
        task.title = request.form['title']
        db.session.commit()
        return redirect(url_for('task_bp.list_tasks'))
    return render_template('update_task.html', task=task)


@task_bp.route('/delete/<int:task_id>', method=['DELETE'])
def delete_task(task_id):
    task = Task.query.get_or_404(task_id)
    db.session.delete(task)
    db.session.commit()
    return redirect(url_for('task_bp.list_tasks'))


templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To-Do List</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="container">
        <h1>To-Do List App</h1>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/create_task.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" class="task-form">
    <label for="title">Titulo da tarefa:</label>
    <input type="text" name="title" placeholder="Digite o nome da tarefa" required>
    <button type="submit">Adicionar</button>
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<a class="btn" href="{{ url_for('task_bp.create') }}">+ Nova tarefa</a>
<ul>
    {% for task in tasks %}
        <li>
            <span>{{ task.title }}</span>
            <a class="delete" href="{{ url_for('task_bp.delete', task_id=task.id) }}">Excluir</a>
        </li>
    {% else %}
        <li>Nenhuma tarefa adicionada ainda</li>
    {% endfor %}
</ul>
{% endblock %}